name: button_project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  badges: ^3.1.1
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.0.0+3
  sizer: ^2.0.15
  another_flushbar: ^1.12.30
  curved_progress_bar: ^1.0.2
  flutter_bloc: ^8.1.3
  audioplayers: ^4.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
